#!/bin/bash

set -euxo pipefail

cd "$(dirname "$0")"

# requires toml package (apt-get install python3-toml)
CLI_VERSION="$(python -c 'import toml; fh = open("Cargo.toml"); data = toml.load(fh); print(data["package"]["version"])')"
export CLI_VERSION

build_and_upload() {
  local target="$1"
  local artefact="$2"
  echo "Building version $CLI_VERSION ($target: $artefact)"

  cargo build --release --target "$target"

  # Upload executables if they do not already exist
  export VERSIONED_GS_PATH="gs://reinfer-public/cli/bin/${target}/${CLI_VERSION}/$artefact"
  export LATEST_GS_PATH="gs://reinfer-public/cli/bin/${target}/latest/$artefact"

  if ! gsutil -q stat "$VERSIONED_GS_PATH"; then
    gsutil cp "../target/${target}/release/$artefact" "$VERSIONED_GS_PATH"
  fi

  # TODO (tommmiligan) Disable until we can ove