#!/bin/bash

set -ex

case $BUILD_PLATFORM in
  "ubuntu-20.04")
    rustup target add x86_64-unknown-linux-musl
    sudo apt-get install          \
      musl-tools                  \
      python3-toml
    cargo install cargo-deb
    ;;
  "maco