[package]
name = "reinfer-client"
version = "0.26.0"
description = "API client for Re:infer, the conversational data intelligence platform"
homepage = "https://github.com/reinfer/cli"
readme = "README.md"
authors = ["reinfer Ltd. <eng@